stages:
  - linters
  - tests
{%- if cookiecutter.use_docker != "n" %}
  - build
{%- endif %}
{%- if cookiecutter.heroku_deploy != "n" %}
  - deploy
{%- endif %}

variables:
  POSTGRES_USER: '{{ cookiecutter.project_slug }}'
  POSTGRES_PASSWORD: ''
  POSTGRES_DB: 'test_{{ cookiecutter.project_slug }}'

flake8:
  stage: linters
  image: python:3.7-alpine
  before_script:
    - pip install -q flake8
    - pip install -q flake8-isort
  script:
    - flake8

pytest:
  stage: tests
  image: python:3.7
  coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+\%)$/'
  tags:
    - docker
  services:
    - postgres:11
  variables:
    DATABASE_URL: pgsql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres/$POSTGRES_DB

  before_script:
    - pip install -r requirements/base.txt -r requirements/test.txt

  script:
    - pytest --cov {{ cookiecutter.project_slug }}/apps/
{%- if cookiecutter.use_docker != "n" %}

.build-docker-image:
  stage: build
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$IMAGE_TAG -f docker/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG

build-docker-alpha:
  extends: .build-docker-image
  variables:
    IMAGE_TAG: $CI_COMMIT_REF_SLUG
  when: manual

build-docker-release:
  extends: .build-docker-image
  variables:
    IMAGE_TAG: $CI_COMMIT_TAG
  only:
    - tags
{%- endif %}
{%- if cookiecutter.heroku_deploy != "n" %}

heroku-deploy:
  stage: deploy
  image: 'tmaier/dpl'
  script:
    - dpl --provider=heroku --app={{ cookiecutter.project_slug }} --api-key=$HEROKU_API_KEY
  when: manual
  only:
    - master
{%- endif %}
