version: '3'

volumes:
  postgres_data: {}

services:
  application:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: {{ cookiecutter.project_slug }}_app
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
{%- if cookiecutter.cache_backend == 'memcached' %}
      - memcached
{%- endif %}
    env_file:
      - compose.env.example

  worker:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: {{ cookiecutter.project_slug }}_worker
    command: celery worker -A {{ cookiecutter.project_slug }}.celery --uid nobody -E --loglevel INFO
    depends_on:
      - redis
{%- if cookiecutter.cache_backend == 'memcached' %}
      - memcached
{%- endif %}
    env_file:
      - compose.env.example

  beat:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: {{ cookiecutter.project_slug }}_beat
    command: celery beat -A {{ cookiecutter.project_slug }}.celery --loglevel INFO
    depends_on:
      - redis
{%- if cookiecutter.cache_backend == 'memcached' %}
      - memcached
{%- endif %}
    env_file:
      - compose.env.example

  postgres:
    image: postgres:11-alpine
    ports:
      - 9999:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:5.0

{%- if cookiecutter.cache_backend == 'memcached' %}

  memcached:
    image: memcached
    entrypoint:
      - memcached
      - -m 64
{%- endif %}
